title: InfoSec WriteUps by Zishan Ahamed Thandar
slogan: all you need to kNow
#logo: "assets/uploads/profile.jpg"

# baseurl: ""
url: "https://ZishanAdThandar.github.io"

collections:
  notes:
    output: true

defaults:
  - scope:
      path: ""  # This applies to all files
    values:
      layout: default

plugins:
  - kramdown
  - jekyll-sitemap



