title: "Zishan Hack"
tagline: "Cybersecurity CTF & Bug Bounty Solutions"
url: "https://blog.zishanhack.com"
baseurl: ""
author: "Zishan Ahamed Thandar"
email: "support@zishanhack.com"
description: "Professional cybersecurity writeups, articles, CTF solutions, and bug bounty reports."


# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude
exclude:
  - CNAME
  - node_modules/
  - Gemfile
  - Gemfile.lock

# Social
github: "ZishanAdThandar"
twitter: "zishanadthandar"
linkedin: "zishanadthandar"
youtube: "ZishanAdThandar"
linktree: "https://go.zishanhack.com"
portfolio: "https://portfolio.zishanhack.com"
main_site: "https://zishanhack.com"
sponsors: "https://github.com/sponsors/ZishanAdThandar"

# Build
markdown: kramdown
highlighter: rouge
permalink: pretty
timezone: UTC

