title: InfoSec WirteUps by Zishan Ahamed Thandar
slogan: all you need to kNow
#logo: "assets/uploads/profile.jpg"

# baseurl: ""
url: "https://ZishanAdThandar.github.io"

collections:
  notes:
    output: true
   

defaults:
  - scope:
      path: ""  # This applies to all files
    values:
      layout: default  # This sets the default layout if none is mentioned
      css: "style.css"

  

plugins:
  - kramdown
  - jekyll-auto-index


markdown: kramdown
# paginate: 5
# paginate_path: "/page:num"
